variable  vpc_cidr_block {}
variable  subnet_cidr_block {}
variable  my_ip {}
variable  instance_type {} 
variable  availability_zone {}
variable  public_key_location {}
variable  image_name {}
variable  env-prefix {}
variable instance_names {}