variable  vpc_cidr_block {}
variable  subnet_cidr_block {}
variable  env_prefix {}
variable  my_ip {}
variable  instance_type {} 
variable  instance_type_small {}
variable  availability_zone {}
variable  public_key_location {}
variable  image_name {}